apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mygu13ub8-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mygu13ub8-nodejs 
  name: mygu13ub8-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mygu13ub8-nodejs 
